### ISSUE TITLE
Hentebeskjed-issue, SMS, artikkelkopi

### ISSUE THREAD

**Issue by ewinge** [scriptotek/alma-slipsomat#17]
Hei, melde inn en liten ting:
Hentebeskjed på SMS, på artikkelkopi fra innlånstjenesten vår, har hentenummer (uten dato, men med løpenummer: " -20871" eller noe sånt).
Jeg så dette på låners telefon.
Men eposten (i Attachments) ser bra ut (altså uten hentenummer). 
Mulig dette er gjennomgående, men at vi ikke har sett det tidligere, fordi det bare gjelder SMS og ikke epost?

Borrowing request: 47bibsysubo0005722
Hentebeskjedene sendt 13/5.

Øystein

**Comment by danmichaelo** [comment]
Jaa, stemmer. I `FulPlaceOnHoldShelfLetter` har vi en sjekk på om  `notification_data/request/work_flow_entity/expiration_date` er blank, som mangler i sms-versjonen.. Det beste hadde sikkert vært å skilt ut hele hentenummer-greia i en mal, så vi slapp å duplisere koden i to (tre?) filer.

**Comment by danmichaelo** [comment]
Tror det skal være fiksa nå. Tester

**Comment by danmichaelo** [comment]
Måtte tilbakestille. Det funka lokalt med xsltproc, men ser ikke ut som det funka å legge til en ny include (`<xsl:include href="header.xsl" />`) i `SmsFulPlaceOnHoldShelfLetter.xsl`. Argh.

**Comment by danmichaelo** [comment]
Som nevnt i commit-meldingen: fant ut at `mailReason.xsl` lot seg inkludere i  `SmsFulPlaceOnHoldShelfLetter.xsl`, så da kan vi ha malene der. Forstår fortsatt ikke hvorfor inklusjon av `header.xsl` førte til at sms ikke lenger ble sendt ut, men prøvde på nytt og det funka fortsatt ikke. Uten feilmeldinger, og uten mulighet til å teste sms under "notification template", er det temmelig håpløst å debugge..
