### ISSUE TITLE
Kvittering for utlån

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/alma-slipsomat#19]
Oppsummerer epostutveksling:

@ewinge : 

> Vi skulle gjerne hatt mulighet for å skrive ut kvitteringer for lån fra alma, feks for bruk som adresselapp. Er det noe dere har drøftet?

@GeirNordanger : 

> Foreslår at du og Anne Gunn tester. For å skru på for en skranke: fulfillment configuration -> you are configuring -> biblioteket du vi teste med -> cirkulation desk -> default-> printing information

**Comment by ewinge** [comment]
Anne Gunn:

> jeg gjorde alt Geir sa under her, men ingenting kom.

@GeirNordanger : 

> Det oppklarende. Det dere skrudde på(på min oppfordring) var å sende lånekvittering automatisk til låner på epost. 
> Altså samme funksjon som man manuelt kan trykke på ved utlån. 
> Da må jeg titte mer på det. gir jo ingen menig at det ikke skal være kvittering andre steder enn mail.

**Comment by danmichaelo** [comment]
@GeirNordanger:

> Vi fant ut hvordan man satte på print av kvittering og retur, men det blir automatisk på alt dessverre. 
> 
> Sjekker litt mer til uka og sender inn sak/spørsmål til bibsys på det til uka.

**Comment by danmichaelo** [comment]
@GeirNordanger:

> Da er saken meldt bibsys. 
> 
> Som vi fant ut tidligere ligger problemet i at man ikke får valgt kvitteringsdestinasjon ved manuel kvitteringsskriving.
> 
> Det kan løses midlertidig ved å sette på automatisk printing til cirk.desk printer. Da kommer det trykt kvittering når man trykker på Done (takk til Christine som fant ut detta). Jeg har aldri trykka done....
> 
> Denne midlertidige løsningen kommer vel litt ann på om folk pleier å trykke done eller ikke.

**Comment by danmichaelo** [comment]
This issue was moved to scriptotek/alma-letters-ubo#2
