### ISSUE TITLE
 test command

### ISSUE THREAD

**Issue by ewinge** [scriptotek/alma-slipsomat#20]
Testing  templates in Alma's `notification template` is cumbersome. It would be useful with a `test` command for automated testing. This requires access to XML test data.This can be accomplished in different ways:
- a configurable path to an XML folder
- include XML data in this project. Since the data files include personal data, the repository must then be made private

**Comment by danmichaelo** [comment]
Agree. I've been thinking about that as well.  I suggest we include anonymized xml files in the public repo. If we are not sure that we can anonymize properly, we can instead use xml files from actions involving our own users or some dummy user. We could start with a small set and expand.

We could also use https://developers.exlibrisgroup.com/blog/Alma-letters-XML-samples-for-working-on-XSL-customization , but I've found some of them to produce somewhat strange results, perhaps they're outdated. Still better than nothing.

**Comment by ewinge** [comment]
Right, we have a test user for this: Per Test.

Anonymizing large documents is demanding. Maybe a script to extract strings from XML data would help?

**Comment by danmichaelo** [comment]
I guess gathering samples from a test user is probably the better approach. It shouldn't take too much time to gather samples for the most-used letters, I guess. For some letters, like FulReasourceRequestLeter, we need samples for several cases, though.

I don't have a test user at hand, but I could create one, or get the credentials for an existing one.

**Comment by ewinge** [comment]
what's the working directory of Firefox?

**Comment by danmichaelo** [comment]
The user profile folder?
