### ISSUE TITLE
Shell library 

### ISSUE THREAD

**Issue by ewinge** [scriptotek/alma-slipsomat#22]
We should use  a  readline library. Maybe Pythons Cmd class?

**Comment by ewinge** [comment]
cc139e9 fails on Python 2. Should we still support it?

**Comment by danmichaelo** [comment]
In this case it was trivial to fix, so I fixed it. But if it becomes a real burden, we should drop it.

**Comment by danmichaelo** [comment]
Great addition btw.! Now it's very tempting to add commands for checking out and returning books…
