### ISSUE TITLE
"local variable 'defaults_filename' referenced before assignment"

### ISSUE THREAD

**Issue by thomfray** [scriptotek/alma-slipsomat#36]
Hi Dan

Just watched your presentation at the 2018 IGeLU Developers Day. This looks like a great tool! I've installed it but am getting an error when I run the _defaults_ command.

The traceback I'm gettiing is below. Any thoughts on what I'm missing?

[1/114] SmsFulUserOverdueNoticeLetter.xsl                            checking...
Exception: local variable 'defaults_filename' referenced before assignment
Traceback (most recent call last):
  File "c:\anaconda3\lib\site-packages\slipsomat\shell.py", line 182, in execute
    fn(*args, **kwargs)
  File "c:\anaconda3\lib\site-packages\slipsomat\slipsomat.py", line 443, in pull_defaults
    local_storage.store_default(filename, content)
  File "c:\anaconda3\lib\site-packages\slipsomat\slipsomat.py", line 145, in store_default
    defaults_filename = os.path.join('defaults', defaults_filename)
UnboundLocalError: local variable 'defaults_filename' referenced before assignment

Thanks
Tony

**Comment by danmichaelo** [comment]
If you installed it using pip, try `pip install -U alma-slipsomat`. I had forgotten to push the latest version there. Let me know if you still have issues.

**Comment by danmichaelo** [comment]
Yeah, I'm quite sure this is a typo I fixed [in August](https://github.com/scriptotek/alma-slipsomat/commit/76b603455b961bf9e25c37ffb3c7d2943970a2dd). Enjoy :)

**Comment by thomfray** [comment]
Thanks for your response Dan and (hopefully) a quick resolution! 
I’ll have a try the reinstall when I get the chance and let you know how it goes – hopefully later this week. 
Cheers
Tony

**Comment by thomfray** [comment]
Everything seems to be working fine now Dan. The defaults are all downloaded and our live production versions are in the process of being pulled.
Thanks for fixing the issue so quickly, and thanks again for the actual tool itself.
My next task is to think how to integrate with our current workflow and Git repo :)
Cheers, Tony
