### ISSUE TITLE
Pip installing an old version ? 

### ISSUE THREAD

**Issue by symac** [scriptotek/alma-slipsomat#37]
Hello,
trying to install slipsomat using instrucintions from the readme (```pip install -U slipsomat```) I can see that the version installed is 0.2.4 when according to what I can see in the files there has been two versions meanwhile.
As I have a timeout I suspect it might be because of the version I use, would it be possible to push the 0.2.6 version to pip?

**Comment by danmichaelo** [comment]
Ouch, I forgot to upload to pypi. Now it should be updated!

https://pypi.org/project/slipsomat/
