### ISSUE TITLE
Pickup location is sometimes missing

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/alma-slipsomat#5]
## Affected
- [FulPlaceOnHoldShelfLetter.xsl](https://github.com/scriptotek/alma-slipsomat/blob/master/xsl/letters/FulPlaceOnHoldShelfLetter.xsl)
- [SmsFulPlaceOnHoldShelfLetter.xsl](https://github.com/scriptotek/alma-slipsomat/blob/master/xsl/letters/sms/SmsFulPlaceOnHoldShelfLetter.xsl)
## Steps
- Go to `Receiving items`
- Select 'External identifer', check 'automatically notify patron', select 'Physical non-returnable', enter 'external identifier' and check 'complete the request'.
- A message is sent to the requester that the document can be picked up, but the pickup location is missing because `notification_data/request/assigned_unit_name` is blank.
## Note

The xml letters also contains a promising-looking field called `pickup_location_str`, but this is always blank. When [asking](https://developers.exlibrisgroup.com/forum/posts/list/273.page) about it on the Developer Network forum, I got the reply:

> pickup_location_str is a transient field that was not meant to be part of the letter. 
> You should not use it, and we should remove it from the letter to avoid confusion.

**Comment by danmichaelo** [comment]
For `physical_non_returnable`, it seems like `notification_data/phys_item_display/owning_library_name` is set to the name that receives the document, so I added that as a fallback.

I also replaced `notification_data/request/assigned_unit_name` with `notification_data/request/delivery_address`, which, despite the misleading name, seems to be just the library name without the name of the circulation desk (whenever  `notification_data/request/assigned_unit_name` is blank, so is `notification_data/request/delivery_address`). Examples:
- `<assigned_unit_name>UiO Informatikkbiblioteket - Utlånet Inf</assigned_unit_name>
  <delivery_address>UiO Informatikkbiblioteket</delivery_address>`
- `<assigned_unit_name>UiO Realfagsbiblioteket - Utlånet Ureal</assigned_unit_name> <delivery_address>UiO Realfagsbiblioteket</delivery_address>`

**Comment by ewinge** [comment]
fixed?

**Comment by danmichaelo** [comment]
Hope so!
