### ISSUE TITLE
Vise temporary location

### ISSUE THREAD

**Issue by danmichaelo** [scriptotek/alma-slipsomat#7]
Ful resource request slip letter (?)(pick-from-shelf-slip'en): Ønske om å vise temporary location (Eks. fra HumSam: "Nyhetshylle", "ny skjønnlitteratur", "fjernlån"). 

Fra: https://trello.com/c/s3CDNcrb/23-ful-resource-request-slip-letter-pick-from-shelf-slip-en-nske-om-temporary-location-eks-fra-humsam-nyhetshylle-ny-skj-nnlitterat

**Comment by ewinge** [comment]
XML-en har:
&lt;location_code&gt;k00009&lt;/location_code&gt;
&lt;location_name&gt;UHS (k00009)&lt;/location_name&gt;
&lt;permanent_location /&gt;
&lt;permanent_physical_location /&gt;

**Comment by ewinge** [comment]
test data: 
\kant\ub-felles\Prosjekter\alma\almaletters\xml-kildefiler\FulReasourceRequestSlipLetter-temporary-location.xml

The temporary location:

```
    <available_items>
        <available_item>
            <barcode>15k808114</barcode>
            <call_number>Ung 839.82 Løk:Ulv</call_number>
            <item_policy></item_policy>
            <library_code>1030300</library_code>
            <library_name>UiO HumSam-biblioteket</library_name>
            <location_code>k10010</location_code>
            <location_name>UHS Ny skjønnlitteratur</location_name>
            <material_type>BOOK</material_type>
            <public_note></public_note>
            <shelving_location></shelving_location>
        </available_item>
    </available_items>
    <barcode></barcode>
```
